module.exports = {
  projects: [
    '<rootDir>/apps/api',
    '<rootDir>/libs/interfaces',
    '<rootDir>/libs/dto',
    '<rootDir>/apps/client',
    '<rootDir>/apps/admin',
    '<rootDir>/libs/ui',
    '<rootDir>/libs/client/storefront',
    '<rootDir>/libs/client/auth',
    '<rootDir>/libs/api/auth',
    '<rootDir>/libs/api/user',
    '<rootDir>/libs/api/shop-item',
    '<rootDir>/libs/entities',
    '<rootDir>/libs/material',
    '<rootDir>/libs/admin/users',
    '<rootDir>/libs/admin/dashboard',
    '<rootDir>/libs/api/shared',
    '<rootDir>/libs/admin/products',
  ],
};
